# Generated by Django 4.1.7 on 2023-02-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categorycost', models.CharField(max_length=30, unique=True, verbose_name='Наименование категории расхода ДС')),
                ('plan', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Планируемое значение расхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование расхода')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма расхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание расхода')),
                ('plan', models.BooleanField(default=False, verbose_name='Плановое поступление')),
                ('permanent_income', models.BooleanField(default=False, verbose_name='Постоянный доход')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main_app.bill', verbose_name='Счет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main_app.categoryincome')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main_app.currency', verbose_name='Валюта')),
            ],
        ),
    ]
