# Generated by Django 4.1.7 on 2023-02-28 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_categorycost_incomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поступления'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование поступления'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма поступления'),
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование расхода')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма расхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание расхода')),
                ('plan', models.BooleanField(default=False, verbose_name='Плановый расход')),
                ('permanent_cost', models.BooleanField(default=False, verbose_name='Постоянный расход')),
                ('bound_cost', models.BooleanField(default=False, verbose_name='Обязательный расход')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='main_app.bill', verbose_name='Счет')),
                ('category_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='main_app.categorycost')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='main_app.currency', verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budjetname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budjet', to='main_app.budjetname')),
                ('costs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budjet', to='main_app.costs')),
                ('incomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budjet', to='main_app.incomes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budjet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
