# Generated by Django 4.1.7 on 2023-02-28 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_incomes_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='creation_date',
            field=models.DateField(default=datetime.date(2023, 2, 28), verbose_name='Дата создания'),
        ),
    ]
