# Generated by Django 4.1.7 on 2023-02-28 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_costs_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
